### PR TITLE
Improve child_process stdio & support passing extra cli args

### PR DESCRIPTION
**Pull request by loklaan**
Hey folks!

Great CLI idea.

I've fixed:

* shell escape issues caused by deps with version ranges. eg `>=15.5.4 <=16.0.0` would break cli
* added an example for using the cli in `package.json` scripts, which I consider a core use case

### CODE REVIEW

**Comment by loklaan** [comment]
Hmm, that travis check doesn't seem to be actually setup. You'll have to pull down the changes to test, sorry.

**Comment by jshthornton** [comment]
@loklaan just fixing up travis and then will merge.

**Comment by jshthornton** [comment]
@loklaan released as v1.1.0

**Comment by loklaan** [comment]
@jshthornton Solid - thanks for the super-quick release!

**Pull request merged**
